name: tryandbuy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  api_cache_manager: ^1.0.1
  flutter_material_design_icons: ^1.1.7447
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  arcore_flutter_plugin: ^0.2.0-alpha
  permission_handler: ^11.3.1
  google_ml_kit: ^0.16.3
  camera: ^0.10.5+9
  image_picker: ^1.0.8
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
